---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: wheezy
  driver_config:
    box: debian-7.0-amd64-wheezy-chef-11.4.4.box
    box_url: https://dl.dropboxusercontent.com/s/si19tbftilcuipz/debian-7.0-amd64.box

suites:
- name: emacs24
  run_list:
  - recipe[emacs24]
  attributes: {
    emacs24: {
      build_dir: "/opt/emacs"
    }
  }
